#!/bin/sh

source ./compile-env

cd $SOURCE_DIR/ffmpeg*

#make uninstall
#make clean

./configure \
--prefix="${TARGET_DIR}" \
--pkg-config-flags="--static" \
--extra-cflags="-static -I${TARGET_DIR}/include" \
--extra-cxxflags="-static -I${TARGET_DIR}/include" \
--extra-ldflags="-fopenmp -L${TARGET_DIR}/lib -Wl,-z,muldefs" \
--enable-small \
--disable-debug \
--enable-static \
--disable-ffplay \
--disable-ffserver \
--disable-doc \
--disable-devices \
--disable-hwaccels \
--disable-sdl \
--disable-xlib \
--enable-avresample \
--enable-gpl --enable-version3 --enable-nonfree \
--enable-gray --enable-runtime-cpudetect \
--enable-fontconfig \
--enable-libbluray \
--enable-libfreetype \
--enable-ladspa \
--enable-libfaac \
--enable-libfdk-aac \
--enable-libmp3lame \
--enable-libopus \
--enable-libtheora \
--enable-libvorbis \
--enable-libx264 \
--enable-libx265 \
--enable-libxvid \
--enable-libvpx \
--enable-bzlib \
--enable-zlib \
--enable-libopenh264 \
--enable-libbs2b \
--enable-libcaca \
--enable-libcdio \
--enable-libgme \
--enable-libgsm \
--enable-libilbc \
--enable-libmodplug \
--enable-libnut \
--enable-libopencore-amrnb \
--enable-libopencore-amrwb \
--enable-libopenjpeg \
--enable-libsoxr \
--enable-libshine \
--enable-libspeex \
--enable-libtwolame \
--enable-libutvideo \
--enable-libwavpack \
--disable-libxcb \
--disable-libxcb-shm \
--disable-libxcb-xfixes \
--disable-libxcb-shape
make -j $jval && make install

#-Wl,-z,muldefs # if symbol conflict
#--enable-libaacplus \  # conflict with libfdk_aac
#--enable-libcelt \  # default decoder is available
#--enable-libshine \ # conflict with mp3lame
