#!/bin/sh

export TARGET_DIR=`pwd`/build_dir
export SOURCE_DIR=`pwd`/src_dir
export PKG_CONFIG="$(which pkg-config) --static"

if [ ! -e $TARGET_DIR ];then
	mkdir $TARGET_DIR
	mkdir -p $TARGET_DIR/lib
	ln -s $TARGET_DIR/lib $TARGET_DIR/lib64
fi

if [ ! -e $SOURCE_DIR ];then
	mkdir $SOURCE_DIR
fi

export PKG_CONFIG_PATH="${TARGET_DIR}/lib/pkgconfig"
export PKG_CONFIG_LIBDIR="${TARGET_DIR}/lib/pkgconfig"

export PATH="${TARGET_DIR}/bin:$PATH"

export LDFLAGS="-L$TARGET_DIR/lib/"
export CFLAGS="-I$TARGET_DIR/include/"
export CXXFLAGS="-I$TARGET_DIR/include/"
export CPPFLAGS="-I$TARGET_DIR/include/"

export jval=`nproc`
