#!/bin/bash

source ./compile-env
cd $SOURCE_DIR

SOURCE=$1

SCHEME=`echo $SOURCE | sed 's/^\(.*\):\/\/.*$/\1/'`
FILENAME=`basename "$SOURCE" | sed 's/\?.*//'`
EXTNAME=`echo $FILENAME | sed 's/^.*\.\(.*\)$/\1/'`


if [ "$SCHEME" == "git" ] || [ "$EXTNAME" == "git" ]
then
	if [ -e ${FILENAME%%.git} ]; then
		cd ${FILENAME%%.git}
		git fetch --depth 1 || git fetch
		git checkout -- .
		git clean -f
		git rebase -f master
		cd ..
	else
		git clone $SOURCE --depth 1 || git clone $SOURCE
	fi
elif [ "$SCHEME" == "http" ] || [ "$SCHEME" == "https" ] || [ "$SCHEME" == "ftp" ]
then
	curl -L -o "$FILENAME" "$SOURCE"
	if [ "$EXTNAME" == "zip" ]; then
		unzip -o "$FILENAME"
	else
		tar xvf "$FILENAME"
	fi
elif [ "$SCHEME" == "hg+http" ] || [ "$SCHEME" == "hg+https" ]
then
	if [ -e ${FILENAME} ]; then
		cd ${FILENAME}
		hg pull
		hg update -C
		cd ..
	else
		hg clone ${SOURCE##hg+}
	fi
else
	echo Unknown scheme: $SCHEME
fi

