#!/bin/sh

# needs automake, cmake, imake, apache-ant(libbluray)

./fetch https://github.com/yasm/yasm.git # required by ffmpeg
./fetch http://www.nasm.us/pub/nasm/releasebuilds/2.11.08/nasm-2.11.08.tar.xz
./fetch http://zlib.net/zlib-1.2.8.tar.xz # required by libpng
./fetch http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
./fetch http://git.tukaani.org/xz.git
#./fetch http://www.freedesktop.org/software/vaapi/releases/libva/libva-1.5.1.tar.bz2
#./fetch git://people.freedesktop.org/~aplattner/libvdpau
./fetch http://downloads.sourceforge.net/project/libpng/libpng16/1.6.17/libpng-1.6.17.tar.xz # required by libbluray and many others
./fetch http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.xz # required by libvorbis
./fetch http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.5.tar.xz # required by libtheora
./fetch http://downloads.xiph.org/releases/theora/libtheora-1.2.0alpha1.tar.xz
./fetch https://github.com/webmproject/libvpx.git
./fetch http://downloads.sourceforge.net/faac/faac-1.28.tar.bz2
./fetch ftp://ftp.videolan.org/pub/x264/snapshots/last_x264.tar.bz2
./fetch http://downloads.xvid.org/downloads/xvidcore-1.3.3.tar.gz
./fetch http://downloads.sourceforge.net/project/lame/lame/3.99/lame-3.99.5.tar.gz
./fetch http://downloads.xiph.org/releases/opus/opus-1.1.tar.gz
./fetch https://github.com/cisco/openh264.git
./fetch ftp://oss.sgi.com/www/projects/libnuma/download/nuactl-2.0.10.tar.gz
./fetch hg+https://bitbucket.org/multicoreware/x265
./fetch https://github.com/mstorsjo/fdk-aac.git
./fetch http://download.savannah.gnu.org/releases/freetype/freetype-2.5.5.tar.gz # also required by libbluray and other libs
./fetch http://www.freedesktop.org/software/fontconfig/release/fontconfig-2.11.93.tar.bz2
./fetch https://files.dyne.org/frei0r/releases/frei0r-plugins-1.4.tar.gz
./fetch http://tipok.org.ua/downloads/media/aacplus/libaacplus/libaacplus-2.0.2.tar.gz
./fetch http://www.ladspa.org/download/ladspa_sdk.tgz
./fetch git://anongit.freedesktop.org/fribidi/fribidi # required by libass
./fetch https://github.com/libass/libass.git
./fetch git://git.gnome.org/libxml2 # required by libbluray
./fetch https://github.com/cgwalters/expat-git-mirror.git # required by libbluray
./fetch git://git.videolan.org/libudfread.git # optional required by libbluray
./fetch git://git.videolan.org/libbluray.git
./fetch https://github.com/Distrotech/libaacplus.git
./fetch http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.25.tar.gz # required by libb2sb
./fetch http://downloads.sourceforge.net/project/bs2b/libbs2b/3.1.0/libbs2b-3.1.0.zip
./fetch http://caca.zoy.org/files/libcaca/libcaca-0.99.beta19.tar.gz
./fetch http://downloads.xiph.org/releases/celt/celt-0.11.1.tar.gz
./fetch git://git.sv.gnu.org/libcdio.git
./fetch http://www.speech.cs.cmu.edu/flite/packed/flite-1.4/flite-1.4-release.tar.bz2
./fetch https://bitbucket.org/mpyne/game-music-emu.git
./fetch  http://libgsm.sourcearchive.com/downloads/1.0.13-4/libgsm_1.0.13.orig.tar.gz
./fetch https://github.com/TimothyGu/libilbc.git
./fetch https://github.com/Konstanty/libmodplug.git
./fetch git://git.ffmpeg.org/nut
./fetch http://downloads.sourceforge.net/project/opencore-amr/opencore-amr/opencore-amr-0.1.3.tar.gz
./fetch http://downloads.sourceforge.net/project/openjpeg.mirror/2.1.0/openjpeg-2.1.0.tar.gz
./fetch http://downloads.sourceforge.net/project/quvi/0.9/libquvi/libquvi-0.9.4.tar.xz

./fetch git://source.ffmpeg.org/ffmpeg.git
